{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import flask\n",
    "import pickle\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "filename = 'lm.pkl'\n",
    "lm=pickle.load(open(filename, 'rb'))\n",
    "\n",
    "filename = 'rf.pkl'\n",
    "rf=pickle.load(open(filename, 'rb'))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "app = flask.Flask(__name__, template_folder='templates')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [18/Sep/2020 22:02:42] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Sep/2020 22:02:51] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [18/Sep/2020 22:03:01] \"\u001b[37mPOST / HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "@app.route('/', methods=['GET', 'POST'])\n",
    "def main():\n",
    "    input_variables = pd.DataFrame(columns=['player','inning','against','home','toss_winner'])\n",
    "    if flask.request.method == 'GET':\n",
    "        return(flask.render_template('main.html'))\n",
    "    if flask.request.method == 'POST':\n",
    "        \n",
    "        index=0\n",
    "        team=flask.request.form['team1']\n",
    "        against = flask.request.form['team2']\n",
    "        home=1\n",
    "        selection = flask.request.form['inning']\n",
    "        toss=flask.request.form['toss']\n",
    "        if toss=='team1':\n",
    "            toss_winner=1\n",
    "            if selection=='batting':\n",
    "                inning=1\n",
    "            else :\n",
    "                inning=2\n",
    "        else :\n",
    "            toss_winner=0\n",
    "            if selection=='batting':\n",
    "                inning=2\n",
    "            else :\n",
    "                inning=1\n",
    "        \n",
    "        player = flask.request.form['player1']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "    \n",
    "        player = flask.request.form['player2']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player3']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player4']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player5']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player6']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player7']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player8']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player9']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player10']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player11']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "\n",
    "\n",
    "        \n",
    "        against = flask.request.form['team1']\n",
    "        home=0\n",
    "        selection = flask.request.form['inning']\n",
    "        toss=flask.request.form['toss']\n",
    "        if toss=='team2':\n",
    "            toss_winner=1\n",
    "            if selection=='batting':\n",
    "                inning=1\n",
    "            else :\n",
    "                inning=2\n",
    "        else :\n",
    "            toss_winner=0\n",
    "            if selection=='batting':\n",
    "                inning=2\n",
    "            else :\n",
    "                inning=1\n",
    "        \n",
    "        player = flask.request.form['player12']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "    \n",
    "        player = flask.request.form['player13']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player14']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player15']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player16']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player17']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player18']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player19']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player20']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player21']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        player = flask.request.form['player22']\n",
    "    \n",
    "        input_variables.loc[index,'player']=player\n",
    "        input_variables.loc[index,'inning']=inning\n",
    "        input_variables.loc[index,'against']=against\n",
    "        input_variables.loc[index,'home']=home\n",
    "        input_variables.loc[index,'toss_winner']=toss_winner\n",
    "        index=index+1\n",
    "        \n",
    "        \n",
    "        \n",
    "\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        input_variables.replace(['MS Dhoni','AT Rayudu','KM Asif','DL Chahar','DJ Bravo','F du Plessis','Imran Tahir','Narayan Jagadeesan','KV Sharma','KM Jadhav','L Ngidi','MJ Santner','Monu Singh','M Vijay','RA Jadeja','Ruturaj Gaikwad','SR Watson','SN Thakur','J Hazlewood','PP Chawla','R Sai Kishore','SM Curran','SS Iyer','AM Rahane','A Mishra','Avesh Khan','AR Patel','HV Patel','I Sharma','K Rabada','K Paul','PP Shaw','R Ashwin','RR Pant','S Lamichhane','S Dhawan','A Carey','L Yadav','MP Stoinis','MM Sharma','SO Hetmyer','T Deshpande','D Sams','A Nortje','V Kohli','AB de Villiers','D Padikkal','Gurkeerat Singh','MM Ali','Mohammed Siraj','N Saini','PA Patel','P Negi','S Dube','UT Yadav','Washington Sundar','YS Chahal','AJ Finch','CH Morris','DW Steyn','I Udana','J Philippe','P Deshpande','S Ahamad','A Zampa','RG Sharma','AP Tare','A Singh','AS Roy','DS Kulkarni','HH Pandya','Ishan Kishan','JJ Bumrah','J Yadav','KA Pollard','KH Pandya','MJ McClenaghan','Q de Kock','RD Chahar','S Rutherford','SA Yadav','TA Boult','CA Lynn','D Deshmukh','M Khan','NM Coulter-Nile','Prince Balwant Rai Singh','SS Tiwary','J Pattinson','KL Rahul','Arshdeep Singh','CH Gayle','D Nalkande','K Gowtham','GC Viljoen','Harpreet Brar','J Suchith','KK Nair','Mandeep Singh','MA Agarwal','Mohammed Shami','Mujeeb Ur Rahman','M Ashwin','N Pooran','SN Khan','CJ Jordan','DJ Hooda','GJ Maxwell','Ishan Porel','JDS Neesham','Prabhsimran Singh','R Bishnoi','S Cottrell','T Dhillon','KD Karthik','AD Russell','Kamlesh Nagarkoti','Kuldeep Yadav','LH Ferguson','N Rana','M Prasidh Krishna','RK Singh','S Sandeep Warrier','Shivam Mavi','Shubman Gill','SD Lad','SP Narine','Chris Green','EJG Morgan','M Siddharth','NS Naik','PJ Cummins','Ra Tripathi','Tom Banton','Varun Chakravarthy','SPD Smith','AS Rajpoot','BA Stokes','JC Archer','JC Buttler','MK Lomror','M Vohra','M Markande','R Tewatia','R Parag','SV Samson','Shashank Singh','S Gopal','VR Aaron','Akash Singh','Anirudha Joshi','Anuj Rawat','AJ Tye','DA Miller','JD Unadkat','Kartik Tyagi','O Thomas','RV Uthappa','TK Curran','Yashasvi Jaiswal','DA Warner','Abhishek Sharma','Basil Thampi','B Kumar','B Stanlake','JM Bairstow','KS Williamson','MK Pandey','Mohammad Nabi','Rashid Khan','Sandeep Sharma','S Nadeem','SP Goswami','S Kaul','Khaleel Ahmed','T Natarajan','V Shankar','WP Saha','Abdul Samad','Fabian Allen','MR Marsh','Priyam Garg','Sandeep Bavanaka','Sanjay Yadav','Virat Singh'],['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80','81','82','83','84','85','86','87','88','89','90','91','92','93','94','95','96','97','98','99','100','101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130','131','132','133','134','135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163','164','165','166','167','168','169','170','171','172','173','174','175','176','177','178','179','180','181','182','183','184','185'],inplace=True)\n",
    "        input_variables.replace(['Royal Challengers Bangalore', 'Sunrisers Hyderabad','Rising Pune Supergiant', 'Mumbai Indians','Kolkata Knight Riders', 'Gujarat Lions', 'Kings XI Punjab','Delhi Daredevils', 'Chennai Super Kings', 'Rajasthan Royals','Kochi Tuskers Kerala'],[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],inplace=True)\n",
    "        lm_pred = lm.predict(input_variables)\n",
    "        rf_pred=rf.predict(input_variables)\n",
    "        \n",
    "        \n",
    "        input_variables['lm']=lm_pred\n",
    "        input_variables['rf']=rf_pred\n",
    "        \n",
    "        \n",
    "        \n",
    "        input_variables['player'].replace(['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80','81','82','83','84','85','86','87','88','89','90','91','92','93','94','95','96','97','98','99','100','101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130','131','132','133','134','135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163','164','165','166','167','168','169','170','171','172','173','174','175','176','177','178','179','180','181','182','183','184','185'],['MS Dhoni','AT Rayudu','KM Asif','DL Chahar','DJ Bravo','F du Plessis','Imran Tahir','Narayan Jagadeesan','KV Sharma','KM Jadhav','L Ngidi','MJ Santner','Monu Singh','M Vijay','RA Jadeja','Ruturaj Gaikwad','SR Watson','SN Thakur','J Hazlewood','PP Chawla','R Sai Kishore','SM Curran','SS Iyer','AM Rahane','A Mishra','Avesh Khan','AR Patel','HV Patel','I Sharma','K Rabada','K Paul','PP Shaw','R Ashwin','RR Pant','S Lamichhane','S Dhawan','A Carey','L Yadav','MP Stoinis','MM Sharma','SO Hetmyer','T Deshpande','D Sams','A Nortje','V Kohli','AB de Villiers','D Padikkal','Gurkeerat Singh','MM Ali','Mohammed Siraj','N Saini','PA Patel','P Negi','S Dube','UT Yadav','Washington Sundar','YS Chahal','AJ Finch','CH Morris','DW Steyn','I Udana','J Philippe','P Deshpande','S Ahamad','A Zampa','RG Sharma','AP Tare','A Singh','AS Roy','DS Kulkarni','HH Pandya','Ishan Kishan','JJ Bumrah','J Yadav','KA Pollard','KH Pandya','MJ McClenaghan','Q de Kock','RD Chahar','S Rutherford','SA Yadav','TA Boult','CA Lynn','D Deshmukh','M Khan','NM Coulter-Nile','Prince Balwant Rai Singh','SS Tiwary','J Pattinson','KL Rahul','Arshdeep Singh','CH Gayle','D Nalkande','K Gowtham','GC Viljoen','Harpreet Brar','J Suchith','KK Nair','Mandeep Singh','MA Agarwal','Mohammed Shami','Mujeeb Ur Rahman','M Ashwin','N Pooran','SN Khan','CJ Jordan','DJ Hooda','GJ Maxwell','Ishan Porel','JDS Neesham','Prabhsimran Singh','R Bishnoi','S Cottrell','T Dhillon','KD Karthik','AD Russell','Kamlesh Nagarkoti','Kuldeep Yadav','LH Ferguson','N Rana','M Prasidh Krishna','RK Singh','S Sandeep Warrier','Shivam Mavi','Shubman Gill','SD Lad','SP Narine','Chris Green','EJG Morgan','M Siddharth','NS Naik','PJ Cummins','Ra Tripathi','Tom Banton','Varun Chakravarthy','SPD Smith','AS Rajpoot','BA Stokes','JC Archer','JC Buttler','MK Lomror','M Vohra','M Markande','R Tewatia','R Parag','SV Samson','Shashank Singh','S Gopal','VR Aaron','Akash Singh','Anirudha Joshi','Anuj Rawat','AJ Tye','DA Miller','JD Unadkat','Kartik Tyagi','O Thomas','RV Uthappa','TK Curran','Yashasvi Jaiswal','DA Warner','Abhishek Sharma','Basil Thampi','B Kumar','B Stanlake','JM Bairstow','KS Williamson','MK Pandey','Mohammad Nabi','Rashid Khan','Sandeep Sharma','S Nadeem','SP Goswami','S Kaul','Khaleel Ahmed','T Natarajan','V Shankar','WP Saha','Abdul Samad','Fabian Allen','MR Marsh','Priyam Garg','Sandeep Bavanaka','Sanjay Yadav','Virat Singh'],inplace=True)\n",
    "        input_variables['against'].replace([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],['Royal Challengers Bangalore', 'Sunrisers Hyderabad','Rising Pune Supergiant', 'Mumbai Indians','Kolkata Knight Riders', 'Gujarat Lions', 'Kings XI Punjab','Delhi Daredevils', 'Chennai Super Kings', 'Rajasthan Royals','Kochi Tuskers Kerala'],inplace=True)\n",
    "\n",
    "        \n",
    "        \n",
    "        input_variables_lm=input_variables.sort_values(by=['lm'],ascending=False)\n",
    "        input_variables_lm.reset_index(drop=True,inplace=True)\n",
    "        input_variables_rf=input_variables.sort_values(by=['rf'],ascending=False)\n",
    "        input_variables_rf.reset_index(drop=True,inplace=True)\n",
    "        \n",
    "        return flask.render_template('main.html',\n",
    "                                     \n",
    "                                     tables=[input_variables_lm.to_html(classes='data')], titles=input_variables_lm.columns.values,\n",
    "                                     tables1=[input_variables_rf.to_html(classes='data')])\n",
    "if __name__ == '__main__':\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
